export const AI_ERRORS = {
  // Provider Errors
  RATE_LIMIT: "RATE_LIMIT",
  TIMEOUT: "TIMEOUT",
  NETWORK_ERROR: "NETWORK_ERROR",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  MODEL_NOT_FOUND: "MODEL_NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",

  // Response Errors
  INVALID_RESPONSE: "INVALID_RESPONSE",
  EMPTY_RESPONSE: "EMPTY_RESPONSE",

  // Request Errors
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_MESSAGES: "INVALID_MESSAGES",
  INPUT_TOO_LARGE: "INPUT_TOO_LARGE",

  // Router Errors
  NO_PROVIDER_AVAILABLE: "NO_PROVIDER_AVAILABLE",
  MODEL_NOT_SUPPORTED: "MODEL_NOT_SUPPORTED",

  // Safety
  PROMPT_INJECTION: "PROMPT_INJECTION",
  BLOCKED_TOPIC: "BLOCKED_TOPIC",
  UNSAFE_CONTENT: "UNSAFE_CONTENT",

  // Memory
  MEMORY_ERROR: "MEMORY_ERROR",

  // Retrieval
  RETRIEVAL_ERROR: "RETRIEVAL_ERROR",

  // Generic
  UNKNOWN: "UNKNOWN",
};
