export const INTENTS = {
  GREETING: "GREETING",

  GOODBYE: "GOODBYE",

  UNKNOWN: "UNKNOWN",

  PRODUCT_SEARCH: "PRODUCT_SEARCH",

  PRODUCT_INFORMATION: "PRODUCT_INFORMATION",

  PRODUCT_COMPARISON: "PRODUCT_COMPARISON",

  PRODUCT_RECOMMENDATION: "PRODUCT_RECOMMENDATION",

  SIMILAR_PRODUCTS: "SIMILAR_PRODUCTS",

  FEATURED_PRODUCTS: "FEATURED_PRODUCTS",

  PRODUCT_OF_THE_WEEK: "PRODUCT_OF_THE_WEEK",

  BRANDS: "BRANDS",

  CATEGORIES: "CATEGORIES",

  STORE_INFORMATION: "STORE_INFORMATION",

  FRAGRANCE_EDUCATION: "FRAGRANCE_EDUCATION",

  ORDER_HELP: "ORDER_HELP",

  SHIPPING: "SHIPPING",

  RETURNS: "RETURNS",

  ACCOUNT_HELP: "ACCOUNT_HELP",

  OUT_OF_SCOPE: "OUT_OF_SCOPE",

  FOLLOW_UP: "FOLLOW_UP",
};
