export const INTENTS = {
  GREETING: "GREETING",

  PRODUCT_SEARCH: "PRODUCT_SEARCH",

  PRODUCT_INFORMATION: "PRODUCT_INFORMATION",

  PRODUCT_RECOMMENDATION: "PRODUCT_RECOMMENDATION",

  PRODUCT_COMPARISON: "PRODUCT_COMPARISON",

  FOLLOW_UP: "FOLLOW_UP",

  FRAGRANCE_EDUCATION: "FRAGRANCE_EDUCATION",

  STORE_INFORMATION: "STORE_INFORMATION",

  CATEGORY: "CATEGORY",

  SIMILAR_PRODUCTS: "SIMILAR_PRODUCTS",

  FEATURED_PRODUCTS: "FEATURED_PRODUCTS",

  PRODUCT_OF_THE_WEEK: "PRODUCT_OF_THE_WEEK",

  BRANDS: "BRANDS",

  CATEGORIES: "CATEGORIES",

  UNKNOWN: "UNKNOWN",
};

export default INTENTS;
