export const INTENTS = {
  GREETING: "GREETING",

  PRODUCT_SEARCH: "PRODUCT_SEARCH",

  PRODUCT_INFORMATION: "PRODUCT_INFORMATION",

  PRODUCT_RECOMMENDATION: "PRODUCT_RECOMMENDATION",

  PRODUCT_COMPARISON: "PRODUCT_COMPARISON",

  FOLLOW_UP: "FOLLOW_UP",

  FRAGRANCE_EDUCATION: "FRAGRANCE_EDUCATION",

  STORE_INFORMATION: "STORE_INFORMATION",

  UNKNOWN: "UNKNOWN",
};

export default INTENTS;
